version: '3'
services:
  app:
    container_name: docker-node
    restart: always
    build: .
    ports:
      - '8000:8000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  client:
    build: ./client
    container_name: docker-client
    ports:
      - '3000:3000'